// TODO: Replace with water-company-specific arg types if backend diverges from electric.
// For now, re-export everything from the electric notifications args as-is.
export type {
  ProjectNotificationScopeArgs,
  ProjectNotificationsListArgs,
  ProjectNotificationsMobileListArgs,
  ProjectNotificationsExportArgs,
  ProjectNotificationsMapTasksArgs,
  ProjectNotificationsEmployeesLocationsArgs,
  CreateProjectNotificationArgs,
  UpdateProjectNotificationArgs,
  ProjectNotificationRejectArgs,
  ProjectNotificationReadStatusArgs,
  ProjectNotificationMobileActionArgs,
  ConfirmLocationArgs,
  EndTaskArgs,
  RequestSiteStatusUpdateArgs,
  SafetyViolationSubmissionStatus,
  SafetyViolationSubmissionItem,
  RequestSafetyViolationArgs,
  ProjectNotificationReassignArgs,
  CreateProjectNotificationNoteArgs,
  CopySiteStatusUpdateArgs,
  ProjectNotificationsChartsArgs,
  SiteStatusTypeValue,
  SiteStatusTypeKeyInput,
  CreateSiteStatusTypeArgs,
  UpdateSiteStatusTypeArgs,
  CreateSiteStatusTypeKeyArgs,
  UpdateSiteStatusTypeKeyArgs,
} from "@/services/api/projects/notifications/types/args";
