export const countryCodes = [
    { value: '+20', label: 'Egypt (+20)', flag: '🇪🇬', code: '+20' },
    { value: '+966', label: 'Saudi Arabia (+966)', flag: '🇸🇦', code: '+966' },
    { value: '+971', label: 'UAE (+971)', flag: '🇦🇪', code: '+971' },
    { value: '+65', label: 'Singapore (+65)', flag: '🇸🇬', code: '+65' },
    { value: '+82', label: 'South Korea (+82)', flag: '🇰🇷', code: '+82' },
    { value: '+34', label: 'Spain (+34)', flag: '🇪🇸', code: '+34' },
    { value: '+52', label: 'Mexico (+52)', flag: '🇲🇽', code: '+52' },
    { value: '+31', label: 'Netherlands (+31)', flag: '🇳🇱', code: '+31' },
    { value: '+90', label: 'Turkey (+90)', flag: '🇹🇷', code: '+90' },
    { value: '+1', label: 'United States (+1)', flag: '🇺🇸', code: '+1' },
    { value: '+44', label: 'United Kingdom (+44)', flag: '🇬🇧', code: '+44' },
    { value: '+91', label: 'India (+91)', flag: '🇮🇳', code: '+91' },
    { value: '+86', label: 'China (+86)', flag: '🇨🇳', code: '+86' },
    { value: '+49', label: 'Germany (+49)', flag: '🇩🇪', code: '+49' },
    { value: '+33', label: 'France (+33)', flag: '🇫🇷', code: '+33' },
    { value: '+81', label: 'Japan (+81)', flag: '🇯🇵', code: '+81' },
    { value: '+39', label: 'Italy (+39)', flag: '🇮🇹', code: '+39' },
    { value: '+7', label: 'Russia (+7)', flag: '🇷🇺', code: '+7' },
    { value: '+55', label: 'Brazil (+55)', flag: '🇧🇷', code: '+55' },
    { value: '+61', label: 'Australia (+61)', flag: '🇦🇺', code: '+61' },
  ];