export const ROUTER = {
  LOGIN: "/login",
  COMPANIES: "/companies",
  HomeStore: "/stores",
  Products: "/stores/products",
  Brands: "/stores/brands",
  Categories: "/stores/categories",
  Terms: "/stores/terms",
  warehouse: "/stores/warehouse",
  Discounts: "/stores/discounts",
  requests: "/stores/requests",
  SocialMedia: "/stores/social-media",
  pagesSettings: "/stores/pages-setting",
  Coupons: "/stores/coupons",
  PaymentMethods: "/stores/payment-methods",
  USERS: "/users",
  SETTINGS: "/settings",
  DASHBOARD: "/dashboard",
  ECOMMERCE: "/ecommerce",
  COMPANY_PROFILE: "/company-profile",
  USER_PROFILE: "/user-profile",
  CLIENT_PROFILE: "/client-profile",
  PROGRAM_SETTINGS: {
    USERS: "/users-settings",
  },
  HR_SETTINGS: "/hr-settings",
  Organizational_Structure: "/organizational-structure",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  AttendanceDeparture: "/attendance-departure",
  Powers: "/powers",
  Programs: "/programs",
  Bouquet: "/bouquet",
  BouquetById: (id: string) => `/bouquet/${id}`,
  BouquetDetailsById: (id: string) => `/bouquetDetails/${id}`,
  CRM: {
    clients: "/clients",
    brokers: "/brokers",
    settings: "/crm-settings",
  },
  DOCS_LIBRARY: "/docs-library",
  ACTIVITIES_LOGS: "/activities-logs",
  TERMS_CONDITIONS: "/stores/terms",
};
