export const ROUTER = {
  LOGIN: "/login",
  COMPANIES: "/companies",
  Products: "/stores/products",
  Brands: "/stores/brands",
  USERS: "/users",
  SETTINGS: "/settings",
  DASHBOARD: "/dashboard",
  ECOMMERCE: "/ecommerce",
  COMPANY_PROFILE: "/company-profile",
  USER_PROFILE: "/user-profile",
  PROGRAM_SETTINGS: {
    USERS: "/users-settings",
  },
  HR_SETTINGS: "/hr-settings",
  Organizational_Structure: "/organizational-structure",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
  AttendanceDeparture: "/attendance-departure",
  Powers: "/powers",
  Programs: "/programs",
  Bouquet: "/bouquet",
  BouquetById: (id: string) => `/bouquet/${id}`,
  BouquetDetailsById: (id: string) => `/bouquetDetails/${id}`,
  CRM: {
    clients: "/clients",
    brokers: "/brokers",
    settings: "/crm-settings",
  },
  DOCS_LIBRARY: "/docs-library",
  ACTIVITIES_LOGS: "/activities-logs",
};
