import type { WorkOrderRow } from "./types";

const baseRow = {
  governorate: "الرياض",
  contractingParty: "شركة الانشاءات",
  type: "توريد",
  price: 500_000,
  indebtedness: 120_000,
  representative: "أحمد علي",
  supervisor: "محمد سعيد",
  guidanceAndRegions: "شمال الرياض",
  route: "خط 12",
  defaultValue: 10_000,
  availableBalance: 85_000,
  cashBalance: 25_000,
  posMachinesCount: 2,
  pcMachinesCount: 1,
  totalMachinesCount: 3,
  cashier: "خالد محمد",
  simLinesCount: 2,
  pcSimLinesCount: 1,
  totalLinesCount: 3,
  bank: "الراجحي",
  bankAccountNumber: "SA1234567890",
  bankClientCode: "CL-001",
  bankAccountName: "حساب المحطة",
  collectionParty: "جهة التحصيل المركزية",
  paymentType: "آجل",
  paymentMethod: "تحويل بنكي",
  value: 500_000,
  paymentStatus: "مدفوع",
  active: true,
  block: "A1",
  dataUpdatedAt: "2024-06-15",
  updatedByUser: "admin",
};

export const MOCK_WORK_ORDERS: WorkOrderRow[] = [
  {
    id: "1",
    serial: 1,
    contractCode: "CNT-2024-001",
    clientCode: "CL-1001",
    stationCode: "ST-001",
    stationName: "محطة اليرموك",
    ...baseRow,
  },
  {
    id: "2",
    serial: 2,
    contractCode: "CNT-2024-002",
    clientCode: "CL-1002",
    stationCode: "ST-002",
    stationName: "محطة النخيل",
    ...baseRow,
    governorate: "جدة",
    paymentStatus: "غير مدفوع",
    active: false,
    indebtedness: 250_000,
  },
  {
    id: "3",
    serial: 3,
    contractCode: "CNT-2024-003",
    clientCode: "CL-1003",
    stationCode: "ST-003",
    stationName: "محطة العزيزية",
    ...baseRow,
    governorate: "الدمام",
    type: "تركيب",
    paymentStatus: "جزئي",
  },
  {
    id: "4",
    serial: 4,
    contractCode: "CNT-2024-004",
    clientCode: "CL-1004",
    stationCode: "ST-004",
    stationName: "محطة السلام",
    ...baseRow,
    price: 320_000,
    value: 320_000,
  },
  {
    id: "5",
    serial: 5,
    contractCode: "CNT-2024-005",
    clientCode: "CL-1005",
    stationCode: "ST-005",
    stationName: "محطة الفيصلية",
    ...baseRow,
    contractingParty: "شركة البناء الحديث",
  },
  {
    id: "6",
    serial: 6,
    contractCode: "CNT-2024-006",
    clientCode: "CL-1006",
    stationCode: "ST-006",
    stationName: "محطة الخليج",
    ...baseRow,
    bank: "الأهلي",
  },
  {
    id: "7",
    serial: 7,
    contractCode: "CNT-2024-007",
    clientCode: "CL-1007",
    stationCode: "ST-007",
    stationName: "محطة الواحة",
    ...baseRow,
    paymentStatus: "مدفوع",
    active: true,
  },
  {
    id: "8",
    serial: 8,
    contractCode: "CNT-2024-008",
    clientCode: "CL-1008",
    stationCode: "ST-008",
    stationName: "محطة الملك فهد",
    ...baseRow,
    block: "B2",
    updatedByUser: "user01",
  },
];
