import { DocumentRow } from "../types";

export const MOCK_OUTGOING_DOCUMENTS: DocumentRow[] = [
  {
    id: "1",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
  {
    id: "2",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "approved",
  },
  {
    id: "3",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "partially_approved",
  },
  {
    id: "4",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "rejected",
  },
  {
    id: "5",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
];

export const MOCK_INCOMING_DOCUMENTS: DocumentRow[] = [
  {
    id: "101",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
    documentType: "مراجعة المالية",
    approvalStatus: "عوافقة الحالية",
    submissionDate: "22/000/2023",
    description:
      "الوصف تاريخ الحد من التضخم الوقت دمج تغيير في المقيقات ومطبق العامة والتماثل الاتسع في حل من الشكليات، أسبية والطلبات المستند مواحدتهم صنداليد لوست المفيدة والمعامل والتاسينست من المقيقات، الوقايعية، والحدال التصائية اللنية.",
    attachments: [
      {
        id: "a1",
        name: "مجمع القالب",
        url: "/files/template-1.pdf",
        type: "pdf",
        size: "2 mb",
      },
      {
        id: "a2",
        name: "مجمع القالب",
        url: "/files/template-2.pdf",
        type: "pdf",
        size: "1.5 mb",
      },
      {
        id: "a3",
        name: "مجمع القالب",
        url: "/files/template-3.pdf",
        type: "pdf",
        size: "3 mb",
      },
    ],
    approvalPath: [
      {
        id: "s1",
        title: "تقديم",
        user: "من عدام",
        date: "2023",
        status: "completed",
        icon: "submit",
      },
      {
        id: "s2",
        title: "مراجعة اولية",
        user: "أحمد علي",
        date: "من عدام 2023",
        status: "completed",
        icon: "review",
      },
      {
        id: "s3",
        title: "اعتماد فني",
        user: "سارة حسن",
        date: "من عدام 2023",
        status: "completed",
        icon: "technical",
      },
      {
        id: "s4",
        title: "موافقة تجارية",
        user: "محمد خالد",
        date: "من عدام 2023",
        status: "completed",
        icon: "commercial",
      },
    ],
    comments: [
      {
        id: "c1",
        user: "أحمد علي",
        date: "من عدام 2023",
        content: "تم اعتماد المستند والموافقة على التعليمات الأولية",
      },
    ],
  },
  {
    id: "102",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
    documentType: "مراجعة المالية",
    approvalStatus: "عوافقة الحالية",
    submissionDate: "22/000/2023",
    description:
      "الوصف تاريخ الحد من التضخم الوقت دمج تغيير في المقيقات ومطبق العامة والتماثل الاتسع في حل من الشكليات.",
    attachments: [
      {
        id: "a4",
        name: "مجمع القالب",
        url: "/files/template-4.pdf",
        type: "pdf",
        size: "2 mb",
      },
      {
        id: "a5",
        name: "مجمع القالب",
        url: "/files/template-5.pdf",
        type: "pdf",
        size: "1.5 mb",
      },
    ],
    approvalPath: [
      {
        id: "s5",
        title: "تقديم",
        user: "من عدام",
        date: "2023",
        status: "completed",
        icon: "submit",
      },
      {
        id: "s6",
        title: "مراجعة اولية",
        user: "أحمد علي",
        date: "من عدام 2023",
        status: "current",
        icon: "review",
      },
    ],
    comments: [],
  },
  {
    id: "103",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
  {
    id: "104",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
  {
    id: "105",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
  {
    id: "106",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
  {
    id: "107",
    name: "ملف الانشاء",
    fileSize: "4 mb",
    documentCount: 3,
    lastActivityUser: "احمد محمد",
    lastActivityDate: "2023",
    status: "draft",
  },
];
