import type {
  DocumentRequirementRow,
  DocumentRequirementStat,
} from "../types";

export const DOCUMENT_REQUIREMENT_STATS: DocumentRequirementStat[] = [
  { key: "awaitingAcceptance", count: 8, percent: 10 },
  { key: "rejected", count: 12, percent: 10 },
  { key: "accepted", count: 127, percent: 10 },
  { key: "inProgress", count: 127, percent: 10 },
  { key: "certified", count: 127, percent: 10 },
];

export const DOCUMENT_REQUIREMENT_MOCK_ROWS: DocumentRequirementRow[] = [
  {
    id: "1",
    requirementCode: "NTF-0001",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "under_review",
    linkedDocument: "KDC-VD-SDR-15",
    completionPercent: 70,
  },
  {
    id: "2",
    requirementCode: "NTF-0002",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "in_progress",
    linkedDocument: "KDC-VD-SDR-15",
    completionPercent: 50,
  },
  {
    id: "3",
    requirementCode: "NTF-0003",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "under_review",
    linkedDocument: "KDC-VD-SDR-15",
    completionPercent: 70,
  },
  {
    id: "4",
    requirementCode: "NTF-0004",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "ميكانيكا",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "in_progress",
    linkedDocument: "KDC-VD-SDR-16",
    completionPercent: 50,
  },
  {
    id: "5",
    requirementCode: "NTF-0005",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "مدني",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "accepted",
    linkedDocument: "KDC-VD-SDR-17",
    completionPercent: 100,
  },
  {
    id: "6",
    requirementCode: "NTF-0006",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Material approval sheet",
    documentType: "Material Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "المقاول",
    reviewingEntity: "الاستشاري",
    frequency: "مرة واحدة",
    submissionStatus: "awaiting_acceptance",
    linkedDocument: "KDC-VD-SDR-18",
    completionPercent: 30,
  },
  {
    id: "7",
    requirementCode: "NTF-0007",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "As-built drawing",
    documentType: "As-Built",
    specialization: "ميكانيكا",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "rejected",
    linkedDocument: "KDC-VD-SDR-19",
    completionPercent: 20,
  },
  {
    id: "8",
    requirementCode: "NTF-0008",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Method statement",
    documentType: "Method Statement",
    specialization: "مدني",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "certified",
    linkedDocument: "KDC-VD-SDR-20",
    completionPercent: 100,
  },
  {
    id: "9",
    requirementCode: "NTF-0009",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "under_review",
    linkedDocument: "KDC-VD-SDR-21",
    completionPercent: 60,
  },
  {
    id: "10",
    requirementCode: "NTF-0010",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "in_progress",
    linkedDocument: "KDC-VD-SDR-22",
    completionPercent: 45,
  },
  {
    id: "11",
    requirementCode: "NTF-0011",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Inspection request",
    documentType: "Inspection",
    specialization: "مدني",
    phase: "المالك",
    sendingEntity: "المقاول",
    reviewingEntity: "الاستشاري",
    frequency: "مرة واحدة",
    submissionStatus: "accepted",
    linkedDocument: "KDC-VD-SDR-23",
    completionPercent: 90,
  },
  {
    id: "12",
    requirementCode: "NTF-0012",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "ميكانيكا",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "under_review",
    linkedDocument: "KDC-VD-SDR-24",
    completionPercent: 55,
  },
  {
    id: "13",
    requirementCode: "NTF-0013",
    requiredDocumentName: "مستند اعتماد موثق",
    document: "Shop drawing - lv panel",
    documentType: "Technical Submittal",
    specialization: "كهرباء",
    phase: "المالك",
    sendingEntity: "الاستشاري",
    reviewingEntity: "المقاول",
    frequency: "مرة واحدة",
    submissionStatus: "in_progress",
    linkedDocument: "KDC-VD-SDR-25",
    completionPercent: 40,
  },
];
