import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import ReactQueryProvider from "@/providers/react-query";

const theSans = localFont({
  src: [
    {
      path: "./fonts/TheSans-Plain.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/TheSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-theSans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" className="dark">
      <body className={theSans.variable}>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
