import type { Metadata } from "next";
import "./[locale]/globals.css";
import localFont from "next/font/local";
import ReactQueryProvider from "@/providers/react-query";
import { Toaster } from "@/modules/table/components/ui/toaster";
import { Toaster as SonnerToaster } from "sonner";
import { ThemeProvider } from "@/providers/theme-provider";
import { cn } from "@/lib/utils";
import CustomThemeProvider from "@/theme/theme";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import NextTopLoader from "nextjs-toploader";

const theSans = localFont({
  src: [
    {
      path: "./fonts/TheSans-Plain.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/TheSans-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-theSans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Constrix",
  description: "Generated by Constrix",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html suppressHydrationWarning>
      <body className={cn(theSans.variable, "!pointer-events-auto")}>
        <NextTopLoader />
        <AppRouterCacheProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <CustomThemeProvider direction="ltr">
              <main>
                <ReactQueryProvider>{children}</ReactQueryProvider>
              </main>
              <Toaster />
              <SonnerToaster />
            </CustomThemeProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
