import { createPermissions as create } from "./default-permissions";

export const PERMISSIONS = {
  user: create("USER"),
  profile: {
    education: create("PROFILE_EDUCATION"),
    certificates: create("PROFILE_CERTIFICATES"),
    qualification: create("PROFILE_QUALIFICATION"),
    addressInfo: create("PROFILE_ADDRESS_INFO"),
    maritalStatus: create("PROFILE_MARITAL_STATUS"),
    courses: create("PROFILE_COURSES"),
    employmentInfo: create("PROFILE_EMPLOYMENT_INFO"),
    familyInfo: create("PROFILE_FAMILY_INFO"),
    cv: create("PROFILE_CV"),
    borderNumber: create("PROFILE_BORDER_NUMBER"),
    privileges: create("PROFILE_PRIVILEGES"),
    contactInfo: create("PROFILE_CONTACT_INFO"),
    bankInfo: create("PROFILE_BANK_INFO"),
    personalInfo: create("PROFILE_PERSONAL_INFO"),
    salaryInfo: create("PROFILE_SALARY_INFO"),
    aboutMe: create("PROFILE_ABOUT_ME"),
    residenceInfo: create("PROFILE_RESIDENCE_INFO"),
    experience: create("PROFILE_EXPERIENCE"),
    workLicense: create("PROFILE_WORK_LICENSE"),
    socialMedia: create("PROFILE_SOCIAL_MEDIA"),
    contractWork: create("PROFILE_CONTRACT_WORK"),
    jobOffer: create("PROFILE_JOB_OFFER"),
    passportInfo: create("PROFILE_PASSPORT_INFO"),
  },
  company: create("COMPANY"),
  companyAccessProgram: create("COMPANY_ACCESS_PROGRAM"),
  package: create("PACKAGE"),
  companyProfile: {
    legalData: create("COMPANY_PROFILE_LEGAL_DATA"),
    officialDocument: create("COMPANY_PROFILE_OFFICIAL_DOCUMENT"),
    branch: create("COMPANY_PROFILE_BRANCH"),
    address: create("COMPANY_PROFILE_ADDRESS"),
    officialData: create("COMPANY_PROFILE_OFFICIAL_DATA"),
    supportData: create("COMPANY_PROFILE_SUPPORT_DATA"),
  },
  organization: {
    branch: create("ORGANIZATION_BRANCH"),
    department: create("ORGANIZATION_DEPARTMENT"),
    jobType: create("ORGANIZATION_JOB_TYPE"),
    users: create("ORGANIZATION_USERS"),
    management: create("ORGANIZATION_MANAGEMENT"),
    jobTitle: create("ORGANIZATION_JOB_TITLE"),
  },
  userProfile: {
    contact: create("USER_PROFILE_CONTACT"),
    identity: create("USER_PROFILE_IDENTITY"),
    data: create("USER_PROFILE_DATA"),
  },
  permission: create("PERMISSION"),
  city: create("CITY"),
  loginWay: create("LOGIN_WAY"),
  state: create("STATE"),
  role: create("ROLE"),
  country: create("COUNTRY"),
  driver: create("DRIVER"),
  identifier: create("IDENTIFIER"),
  subEntity: create("SUB_ENTITY"),
  activityLogs: create("LOG"),
  attendance: {
    settings: create("EMPLOYEE_ATTENDANCE_CONSTRAINTS"),
    attendance_departure: {
      ...create("EMPLOYEE_ATTENDANCE"),
      map: "EMPLOYEE_ATTENDANCE_MAP",
    },
  },
  vacations: {
    settings: {
      leaveType: create("LEAVE_TYPE"),
      leavePolicy: create("LEAVE_POLICY"),
      publicHoliday: create("PUBLIC_HOLIDAY"),
    },
  },
  crm: {
    settings: create("CLIENT_SETTING"),
    broker: create("BROKER"),
    clients: create("CLIENT"),
    pricesOffers: create("PRICE_OFFER"),
    serviceSettings: create("TERM_SERVICE_SETTING"),
    termSettings: create("TERM_SETTING"),
  },
  library: {
    folder: create("FOLDER"),
    file: create("FILE"),
  },
  CMS: {
    categories: create("CATEGORY_WEBSITE_CMS"),
    projects: create("WEBSITE_PROJECT"),
    projectsTypes: create("WEBSITE_PROJECT_SETTING"),
    icons: create("WEBSITE_ICON"),
    mainSettings: create("WEBSITE_HOME_PAGE_SETTING"),
    aboutSetting: create("WEBSITE_ABOUT_US"),
    termsConditions: create("WEBSITE_TERM_AND_CONDITION"),
    news: create("WEBSITE_NEWS"),
    founder: create("FOUNDER"),
    services: create("WEBSITE_SERVICE"),
    ourServices: create("WEBSITE_OUR_SERVICE"),
    communicationSettings: {
      contactData: create("WEBSITE_CONTACT_INFO"),
      addresses: create("WEBSITE_ADDRESS"),
      socialLinks: create("SOCIAL_MEDIA_LINK"),
    },
    themeSetting: create("WEBSITE_THEME"),
    communicationContactMessages: create("WEBSITE_CONTACT_MESSAGE"),
    themes: create("WEBSITE_THEME_SETTING"),
    BookStore: create("WEBSITE_BOOK_STORE"),
  },
  projectType: create("PROJECT_TYPE"),
  projectTerm: create("PROJECT_TERM"),
  projectManagement: create("PROJECT_MANAGEMENT"),
  clientRequest: create("CLIENT_REQUEST"),
  ecommerce: {
    banner: create("ECOMMERCE_BANNER"),
    coupon: create("ECOMMERCE_COUPON"),
    dashboard: create("ECOMMERCE_DASHBOARD"),
    dealDay: create("ECOMMERCE_DEAL_DAY"),
    brand: create("ECOMMERCE_ECO_BRAND"),
    category: create("ECOMMERCE_CATEGORY"),
    product: create("ECOMMERCE_PRODUCT"),
    featureDeal: create("ECOMMERCE_FEATURE_DEAL"),
    flashDeal: create("ECOMMERCE_FLASH_DEAL"),
    order: create("ECOMMERCE_ORDER"),
    socialMedia: create("ECOMMERCE_SOCIAL_MEDIA"),
    warehouse: create("ECOMMERCE_WAREHOUSE"),
    page: create("ECOMMERCE_PAGE"),
    paymentMethod: create("ECOMMERCE_PAYMENT_METHOD"),
  },
  humanResources: {
    charts: create("HUMAN_RESOURCES_CHARTS"),
    procedures: create("HUMAN_RESOURCES_PROCEDURES"),
    services: create("HUMAN_RESOURCES_SERVICES"),
  },
};
