import { getMessages } from "next-intl/server";
import { routing } from "@/i18n/routing";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "@i18n/navigation";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { cookies } from "next/headers";
import type { Metadata } from "next";

const getCompanyDataFromCookies = async () => {
  const cookieStore = await cookies();
  const companyCookie = cookieStore.get("company-data")?.value;
  return companyCookie ? JSON.parse(companyCookie) : null;
};

export async function generateMetadata(): Promise<Metadata> {
  const companyData = await getCompanyDataFromCookies();
  const companyName = companyData?.name || "Constrix";
  return {
    title: {
      default: companyName,
      template: `%s | ${companyName}`,
    },
    description: "Generated by Constrix",
    icons: companyData?.logo
      ? {
          icon: companyData.logo,
          apple: companyData.logo,
        }
      : undefined,
  };
}

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as "ar" | "en")) {
    return notFound();
  }
  const messages = await getMessages();
  const direction = locale === "ar" ? "rtl" : "ltr";
  
  return (
    <div dir={direction}>
      <NextIntlClientProvider messages={messages}>
        <NuqsAdapter>
          {children}
        </NuqsAdapter>
      </NextIntlClientProvider>
    </div>
  );
}
