/**
 * Values match backend `permission_key` (e.g. `PROJECT_EMPLOYEE_VIEW`).
 * Legacy full `name` strings are still accepted by `hasProjectPermissionKey` as fallback.
 */

// Employee (staff)
export const PROJECT_EMPLOYEE_VIEW = "PROJECT_EMPLOYEE_VIEW";
export const PROJECT_EMPLOYEE_LIST = "PROJECT_EMPLOYEE_LIST";
export const PROJECT_EMPLOYEE_CREATE = "PROJECT_EMPLOYEE_CREATE";
export const PROJECT_EMPLOYEE_UPDATE = "PROJECT_EMPLOYEE_UPDATE";
export const PROJECT_EMPLOYEE_DELETE = "PROJECT_EMPLOYEE_DELETE";

// Archive library (attachments / public docs project scope)
export const PROJECT_ARCHIVE_VIEW = "PROJECT_ARCHIVE_VIEW";
export const PROJECT_ARCHIVE_LIST = "PROJECT_ARCHIVE_LIST";
export const PROJECT_ARCHIVE_CREATE = "PROJECT_ARCHIVE_CREATE";
export const PROJECT_ARCHIVE_UPDATE = "PROJECT_ARCHIVE_UPDATE";
export const PROJECT_ARCHIVE_DELETE = "PROJECT_ARCHIVE_DELETE";

// Roles
export const PROJECT_ROLE_VIEW = "PROJECT_ROLE_VIEW";
export const PROJECT_ROLE_LIST = "PROJECT_ROLE_LIST";
export const PROJECT_ROLE_CREATE = "PROJECT_ROLE_CREATE";
export const PROJECT_ROLE_UPDATE = "PROJECT_ROLE_UPDATE";
export const PROJECT_ROLE_DELETE = "PROJECT_ROLE_DELETE";

// Archive cycle (document cycle)
export const PROJECT_ARCHIVE_CYCLE_VIEW = "PROJECT_ARCHIVE_CYCLE_VIEW";
export const PROJECT_ARCHIVE_CYCLE_LIST = "PROJECT_ARCHIVE_CYCLE_LIST";
export const PROJECT_ARCHIVE_CYCLE_CREATE = "PROJECT_ARCHIVE_CYCLE_CREATE";
export const PROJECT_ARCHIVE_CYCLE_UPDATE = "PROJECT_ARCHIVE_CYCLE_UPDATE";
export const PROJECT_ARCHIVE_CYCLE_DELETE = "PROJECT_ARCHIVE_CYCLE_DELETE";

// Maintenance & emergencies (notifications)
export const PROJECT_NOTIFICATION_VIEW = "PROJECT_NOTIFICATION_VIEW";
export const PROJECT_NOTIFICATION_LIST = "PROJECT_NOTIFICATION_LIST";
export const PROJECT_NOTIFICATION_CREATE = "PROJECT_NOTIFICATION_CREATE";
export const PROJECT_NOTIFICATION_UPDATE = "PROJECT_NOTIFICATION_UPDATE";
export const PROJECT_NOTIFICATION_DELETE = "PROJECT_NOTIFICATION_DELETE";
export const PROJECT_NOTIFICATION_EXPORT = "PROJECT_NOTIFICATION_EXPORT";
export const PROJECT_NOTIFICATION_APPROVE = "PROJECT_NOTIFICATION_APPROVE";
export const PROJECT_NOTIFICATION_REJECT = "PROJECT_NOTIFICATION_REJECT";

// Site Status Types
export const PROJECT_NOTIFICATION_SITE_STATUS_TYPE_LIST =
  "PROJECT_NOTIFICATION_SITE_STATUS_TYPE_LIST";
export const PROJECT_NOTIFICATION_SITE_STATUS_TYPE_VIEW =
  "PROJECT_NOTIFICATION_SITE_STATUS_TYPE_VIEW";
export const PROJECT_NOTIFICATION_SITE_STATUS_TYPE_CREATE =
  "PROJECT_NOTIFICATION_SITE_STATUS_TYPE_CREATE";
export const PROJECT_NOTIFICATION_SITE_STATUS_TYPE_UPDATE =
  "PROJECT_NOTIFICATION_SITE_STATUS_TYPE_UPDATE";
export const PROJECT_NOTIFICATION_SITE_STATUS_TYPE_DELETE =
  "PROJECT_NOTIFICATION_SITE_STATUS_TYPE_DELETE";
