import { MediaFile } from "@/types/media-file";
import { ECM_Category } from "../category";
import { ECM_Tax } from "../tax";

export interface ECM_Product {
  id: string;
  name: string;
  description: string;
  price: number;
  sku: string;
  stock: any;
  warehouse_id: string;
  requires_shipping: number;
  unlimited_quantity: number;
  is_taxable: number;
  price_includes_vat: number;
  vat_percentage: any;
  is_visible: number;
  category?: ECM_Category;
  brand: any;
  type: string;
  taxes?: ECM_Tax[];
  details: any[];
  custom_fields: any[];
  seo: any;
  associated_product: any[];
  main_image?: MediaFile;
  other_images?: MediaFile[];
  countries?: Array<{ id: string | number; name?: string; [key: string]: any }>;
  name_ar?: string;
  name_en?: string;
  description_ar?: string;
  description_en?: string;
  category_id?: string;
  sub_category_id?: string;
  sub_sub_category_id?: string;
  brand_id?: string;
  weight?: string | number;
  unit?: string;
  currency?: string;
  gender?: string;
  min_order_quantity?: number;
  discount_type?: string;
  discount_value?: number;
  shipping_amount?: boolean | number;
  shipping_included_in_price?: boolean;
  video_url?: string;
  meta_title?: string;
  meta_description?: string;
  meta_keywords?: string;
  meta_photo?: MediaFile;
  main_photo?: MediaFile;
  other_photos?: MediaFile[];
}
