import { UserActivityT } from "@/modules/user-profile/types/user-activity";

export const LOGS_TYPES_OPTIONS = [
  { value: "all", label: "All" },
  { value: "create", label: "Create" },
  { value: "update", label: "Update" },
  { value: "delete", label: "Delete" },
];

export const LOGS_USERS_OPTIONS = [
  { value: "all", label: "All" },
  { value: "create", label: "Create" },
  { value: "update", label: "Update" },
  { value: "delete", label: "Delete" },
];

export const LOGS_ACTIVITIES: UserActivityT[] = [
  {
    tags: [],
    updated_at: "2023-01-01",
    url: "",
    user_agent: "",
    id: "1",
    user: {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
    },
    title: "Created a new document",
    auditable_id: "1",
    auditable_type: "document",
    created_at: "2023-01-01",
    event: "created",
    ip_address: "127.0.0.1",
  },
  {
    id: "2",
    user: {
      id: "2",
      name: "Jane Doe",
      email: "jane.doe@example.com",
    },
    updated_at: "2023-01-02",
    title: "Updated a document",
    auditable_id: "2",
    auditable_type: "document",
    created_at: "2023-01-02",
    event: "updated",
    ip_address: "127.0.0.1",
    tags: [],
    url: "",
    user_agent: "",
  },
  {
    id: "3",
    user: {
      id: "3",
      name: "John Doe",
      email: "john.doe@example.com",
    },
    updated_at: "2023-01-03",
    title: "Deleted a document",
    auditable_id: "3",
    auditable_type: "document",
    created_at: "2023-01-03",
    event: "deleted",
    ip_address: "127.0.0.1",
    tags: [],
    url: "",
    user_agent: "",
  },
  {
    tags: [],
    updated_at: "2023-01-01",
    url: "",
    user_agent: "",
    id: "4",
    user: {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
    },
    title: "Created a new document",
    auditable_id: "1",
    auditable_type: "document",
    created_at: "2023-01-01",
    event: "created",
    ip_address: "127.0.0.1",
  },
  {
    id: "5",
    user: {
      id: "2",
      name: "Jane Doe",
      email: "jane.doe@example.com",
    },
    updated_at: "2023-01-02",
    title: "Updated a document",
    auditable_id: "2",
    auditable_type: "document",
    created_at: "2023-01-02",
    event: "updated",
    ip_address: "127.0.0.1",
    tags: [],
    url: "",
    user_agent: "",
  },
  {
    id: "6",
    user: {
      id: "3",
      name: "John Doe",
      email: "john.doe@example.com",
    },
    updated_at: "2023-01-03",
    title: "Deleted a document",
    auditable_id: "3",
    auditable_type: "document",
    created_at: "2023-01-03",
    event: "deleted",
    ip_address: "127.0.0.1",
    tags: [],
    url: "",
    user_agent: "",
  },
];
