name: CI/CD Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened, closed, edited]
  push:
    branches:
      - dev
      - stage
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies
        run: yarn install

    # - name: Build Icons
     #   run: npm run build:icons

      - name: Build Next.js App
        run: yarn build

      - name: Archive Build Artifact
        run: tar -czf nextjs-build.tar.gz .next public package.json yarn.lock

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: nextjs-build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    steps:
      - name: Set Deployment ID
        id: set_deployment_id
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "DEPLOYMENT_ID=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            BRANCH_NAME="${{ github.ref_name }}"
            echo "DEPLOYMENT_ID=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      - name: Echo Deployment ID
        run: |
          echo "Deployment ID: $DEPLOYMENT_ID"

      - name: Extract BE_URL
        id: extract_be_url
        run: |
          #!/bin/bash
          set -e  # Exit immediately if a command exits with a non-zero status

          # Determine the event type
          EVENT_NAME="${GITHUB_EVENT_NAME}"

          if [ "$EVENT_NAME" == "pull_request" ]; then
           # For pull_request events, extract the PR body
           PR_BODY=$(jq --raw-output .pull_request.body < "$GITHUB_EVENT_PATH")
           echo "$PR_BODY"
           # Extract BE_URL from PR body using grep
           BE_URL=$(echo "$PR_BODY" | sed -n 's/.*BE_URL:\s*\(https\?:\/\/\S\+\).*/\1/p')

           if [ -z "$BE_URL" ]; then
             # If BE_URL is not provided, derive it based on the branch name
             BRANCH_NAME="${GITHUB_BASE_REF}"
             ALLOWED_ENVS=("dev" "stage" "master")
             VALID=false

             for env in "${ALLOWED_ENVS[@]}"; do
               if [ "$BRANCH_NAME" == "$env" ]; then
                 VALID=true
                 break
               fi
             done

             if [ "$VALID" = false ]; then
               # Default BE_URL for unspecified or invalid environments
               BRANCH_NAME="master"
             fi

             BE_URL="core-be-${BRANCH_NAME}.constrix-nv.com"
           fi
          else
           # For push events, extract the branch name from GITHUB_REF
           BRANCH_NAME="${GITHUB_REF##*/}"
           BE_URL="core-be-${BRANCH_NAME}.constrix-nv.com"
          fi
          echo "BE_URL=${BE_URL}" >> $GITHUB_ENV

      - name: Echo BE URL
        run: |
          echo "BE URL: $BE_URL"

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build

      - name: Copy Artifact via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: 'nextjs-build.tar.gz'
          target: '/home/deployer/nextjs/deployments/${{env.DEPLOYMENT_ID}}/'

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            DEPLOYMENT_ID=${{ env.DEPLOYMENT_ID }}
            BE_URL=${{ env.BE_URL }}

            echo "Deployment ID inside SSH: $DEPLOYMENT_ID"
            echo "BE URL inside SSH: $BE_URL"

            # Create deployment directory
            mkdir -p /home/deployer/nextjs/deployments/${DEPLOYMENT_ID}

            cd /home/deployer/nextjs/deployments/${DEPLOYMENT_ID}

            # Transfer the build artifact
            tar -xzvf nextjs-build.tar.gz -C /home/deployer/nextjs/deployments/${DEPLOYMENT_ID}

            # Navigate to Next.js directory
            cd /home/deployer/nextjs

            export DEPLOYMENT_ID=${DEPLOYMENT_ID}
            export BE_URL=${BE_URL}

             # Set Docker Compose project name
            export COMPOSE_PROJECT_NAME=nextjs-${DEPLOYMENT_ID}

            PROJECT_NAME=nextjs-$DEPLOYMENT_ID
            echo "Starting remove old ID: $PROJECT_NAME"
            # Check if the project is already running
            if docker ps -a --filter "name=$PROJECT_NAME" | grep -w "$PROJECT_NAME"; then
            echo "Existing deployment found for $PROJECT_NAME. Removing..."
            docker rm -f $PROJECT_NAME
            yes|docker image prune
            echo "Existing deployment removed."
            else
            echo "No existing deployment found for $PROJECT_NAME."
            fi

            # Deploy using Docker Compose
            docker-compose -p nextjs-${DEPLOYMENT_ID} up -d --build
      - name: Post Deployment Comment
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **Deployment Successful**

            Your backend has been deployed to the following URL:
            🔗 [FE Preview](https://core-${{ env.DEPLOYMENT_ID }}.constrix-nv.com)  
            🔗 [Backend URL](${{ env.BE_URL }})

  cleanup:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'merged' || github.event.action == 'closed')
    steps:
      - name: Set Deployment ID for Cleanup
        id: set_cleanup_deployment_id
        run: |
          if [ "${{ github.event.pull_request.merged }}" == "false" ]; then
            echo "DEPLOYMENT_ID=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          else
            # Optionally handle merged PRs if you have separate deployments for them
            echo "DEPLOYMENT_ID=pr${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          fi

      - name: Echo Deployment ID for Cleanup
        run: |
          echo "Cleanup Deployment ID: $DEPLOYMENT_ID"

      - name: Cleanup Deployment on Server via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            DEPLOYMENT_ID=${{ env.DEPLOYMENT_ID }}

            echo "Starting cleanup for Deployment ID: $DEPLOYMENT_ID"

            # Navigate to the deployments directory
            cd /home/deployer/nextjs/deployments/

            # Stop and remove Docker services for the specific deployment
            if [ -d "$DEPLOYMENT_ID" ]; then
              echo "Stopping and removing Docker for $DEPLOYMENT_ID"
              docker rm -f $PROJECT_NAME
            else
              echo "Deployment directory $DEPLOYMENT_ID does not exist. Skipping Docker Compose cleanup."
            fi

            # Remove the deployment directory
            echo "Removing deployment directory: /home/deployer/nextjs/deployments/$DEPLOYMENT_ID"
            rm -rf /home/deployer/nextjs/deployments/$DEPLOYMENT_ID/

            echo "Cleanup for $DEPLOYMENT_ID completed successfully."
